In [1]:
# checking 0.3 alpha w2v lexical data 

import pandas as pd 
import numpy as np

In [3]:
original_embeddings = pd.read_csv('../forager/data/lexical_data/100_dim_lexical_data/alpha_0.3_w2v/embeddings.csv')
original_embeddings

,adder,albatross,alligator,alpaca,anchovy,anemone,ant,antelope,ape,asp,...,killer,prairie,asian,american,australian,african,water,rodents,insects,pets
0,-0.019938,-0.076005,-0.060900,-0.072012,-0.099303,-0.057666,0.016123,-0.026781,0.023876,-0.173052,...,-0.010331,-0.111762,-0.086748,-0.118737,-0.095934,-0.046674,-0.159585,-0.123183,-0.151485,-0.011996
1,0.050598,-0.030789,-0.043797,-0.001057,0.049992,-0.000979,-0.054336,0.040920,-0.048264,-0.028595,...,0.015562,-0.015056,-0.091875,-0.071517,-0.077433,-0.008087,-0.064527,-0.061569,-0.023987,-0.084360
2,-0.188316,-0.141069,-0.113043,-0.122454,-0.270426,-0.132258,-0.200331,-0.203979,-0.290277,-0.182208,...,-0.117498,-0.302520,-0.084210,-0.047799,-0.154521,-0.043581,-0.075840,-0.034458,-0.090855,-0.055425
3,0.008902,-0.142017,-0.071520,-0.153906,-0.280098,-0.101931,0.088209,-0.126789,-0.094128,-0.024021,...,-0.032064,-0.115458,-0.078339,-0.091734,-0.125742,-0.050688,0.056760,-0.075576,-0.045660,-0.088887
4,0.070731,-0.009776,-0.035289,-0.064116,0.141123,-0.010630,0.067122,-0.094581,0.014961,0.034551,...,-0.010922,-0.065034,-0.091206,-0.140808,-0.105891,-0.130491,0.069360,-0.168096,-0.090951,-0.225096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,-0.045923,0.078197,-0.045879,0.028757,0.289555,0.072947,-0.186683,0.171906,-0.054160,0.167503,...,0.033506,0.280735,0.048345,0.110901,0.001015,0.000507,-0.069983,0.132321,0.103117,0.040249
196,0.035383,-0.024171,0.061765,-0.030512,0.188412,-0.047657,-0.111279,-0.025154,0.192430,-0.210609,...,0.053062,-0.001804,-0.067523,-0.021220,0.185976,-0.028401,0.013538,0.134827,-0.102725,0.184499
197,-0.070476,-0.093261,-0.117740,0.121373,-0.107254,-0.016018,-0.089012,-0.095312,-0.189504,-0.141498,...,-0.011731,0.065404,0.036912,0.255262,0.340382,0.161336,-0.209678,0.015536,0.213493,0.067708
198,-0.028416,-0.034777,-0.085771,-0.147959,-0.186830,-0.283675,-0.175357,-0.048205,-0.204323,-0.248374,...,-0.018017,-0.111580,-0.189462,-0.108675,0.032477,-0.319487,0.074137,-0.100702,-0.146076,0.052772
199,-0.020344,0.018761,0.014719,-0.058275,0.398699,0.141246,-0.259707,-0.024641,-0.061868,-0.068269,...,0.003392,-0.098777,-0.007758,0.090433,0.205891,0.110075,-0.062674,0.136661,-0.220339,0.164941

In [5]:
old_embeddinngs = pd.read_csv('../old_data/100_0.3_w2v_embeddings.csv')
old_embeddinngs

,adder,albatross,alligator,alpaca,anchovy,anemone,ant,antelope,ape,asp,...,killer,prairie,asian,american,australian,african,water,rodents,insects,pets
0,-0.019938,-0.076005,-0.060900,-0.072012,-0.099303,-0.057666,0.016123,-0.026781,0.023876,-0.173052,...,-0.010331,-0.111762,-0.086748,-0.118737,-0.095934,-0.046674,-0.159585,-0.123183,-0.151485,-0.011996
1,0.050598,-0.030789,-0.043797,-0.001057,0.049992,-0.000979,-0.054336,0.040920,-0.048264,-0.028595,...,0.015562,-0.015056,-0.091875,-0.071517,-0.077433,-0.008087,-0.064527,-0.061569,-0.023987,-0.084360
2,-0.188316,-0.141069,-0.113043,-0.122454,-0.270426,-0.132258,-0.200331,-0.203979,-0.290277,-0.182208,...,-0.117498,-0.302520,-0.084210,-0.047799,-0.154521,-0.043581,-0.075840,-0.034458,-0.090855,-0.055425
3,0.008902,-0.142017,-0.071520,-0.153906,-0.280098,-0.101931,0.088209,-0.126789,-0.094128,-0.024021,...,-0.032064,-0.115458,-0.078339,-0.091734,-0.125742,-0.050688,0.056760,-0.075576,-0.045660,-0.088887
4,0.070731,-0.009776,-0.035289,-0.064116,0.141123,-0.010630,0.067122,-0.094581,0.014961,0.034551,...,-0.010922,-0.065034,-0.091206,-0.140808,-0.105891,-0.130491,0.069360,-0.168096,-0.090951,-0.225096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,-0.045923,0.078197,-0.045879,0.028757,0.289555,0.072947,-0.186683,0.171906,-0.054160,0.167503,...,0.033506,0.280735,0.048345,0.110901,0.001015,0.000507,-0.069983,0.132321,0.103117,0.040249
196,0.035383,-0.024171,0.061765,-0.030512,0.188412,-0.047657,-0.111279,-0.025154,0.192430,-0.210609,...,0.053062,-0.001804,-0.067523,-0.021220,0.185976,-0.028401,0.013538,0.134827,-0.102725,0.184499
197,-0.070476,-0.093261,-0.117740,0.121373,-0.107254,-0.016018,-0.089012,-0.095312,-0.189504,-0.141498,...,-0.011731,0.065404,0.036912,0.255262,0.340382,0.161336,-0.209678,0.015536,0.213493,0.067708
198,-0.028416,-0.034777,-0.085771,-0.147959,-0.186830,-0.283675,-0.175357,-0.048205,-0.204323,-0.248374,...,-0.018017,-0.111580,-0.189462,-0.108675,0.032477,-0.319487,0.074137,-0.100702,-0.146076,0.052772
199,-0.020344,0.018761,0.014719,-0.058275,0.398699,0.141246,-0.259707,-0.024641,-0.061868,-0.068269,...,0.003392,-0.098777,-0.007758,0.090433,0.205891,0.110075,-0.062674,0.136661,-0.220339,0.164941

In [7]:
print(original_embeddings.compare(old_embeddinngs))

       adder          alligator              baboon            basilisk  \
        self    other      self     other      self     other      self
0        NaN      NaN       NaN       NaN  0.000013  0.000013       NaN
6        NaN      NaN       NaN       NaN       NaN       NaN -0.000021
8        NaN      NaN       NaN       NaN       NaN       NaN       NaN
16       NaN      NaN       NaN       NaN       NaN       NaN       NaN
36       NaN      NaN       NaN       NaN       NaN       NaN       NaN
44       NaN      NaN       NaN       NaN       NaN       NaN       NaN
71       NaN      NaN       NaN       NaN       NaN       NaN       NaN
75       NaN      NaN       NaN       NaN       NaN       NaN       NaN
78       NaN      NaN       NaN       NaN       NaN       NaN       NaN
79       NaN      NaN       NaN       NaN       NaN       NaN       NaN
81       NaN      NaN       NaN       NaN       NaN       NaN       NaN
92       NaN      NaN       NaN       NaN       NaN       NaN       NaN
118  0.00001  0.00001       NaN       NaN       NaN       NaN       NaN
121      NaN      NaN       NaN       NaN       NaN       NaN       NaN
124      NaN      NaN       NaN       NaN       NaN       NaN       NaN
125      NaN      NaN       NaN       NaN       NaN       NaN       NaN
133      NaN      NaN       NaN       NaN       NaN       NaN       NaN
138      NaN      NaN       NaN       NaN       NaN       NaN       NaN
149      NaN      NaN       NaN       NaN       NaN       NaN       NaN
156      NaN      NaN       NaN       NaN       NaN       NaN       NaN
163      NaN      NaN       NaN       NaN       NaN       NaN       NaN
166      NaN      NaN       NaN       NaN       NaN       NaN       NaN
177      NaN      NaN       NaN       NaN       NaN       NaN       NaN
180      NaN      NaN       NaN       NaN       NaN       NaN       NaN
184      NaN      NaN       NaN       NaN       NaN       NaN       NaN
185      NaN      NaN  0.000068  0.000068       NaN       NaN       NaN
191      NaN      NaN       NaN       NaN       NaN       NaN       NaN

                   buck            ...       rat             redtail  \
        other      self     other  ...      self     other      self
0         NaN       NaN       NaN  ...       NaN       NaN       NaN
6   -0.000021       NaN       NaN  ...       NaN       NaN       NaN
8         NaN       NaN       NaN  ... -0.000024 -0.000024       NaN
16        NaN       NaN       NaN  ...       NaN       NaN       NaN
36        NaN       NaN       NaN  ...       NaN       NaN       NaN
44        NaN       NaN       NaN  ...       NaN       NaN       NaN
71        NaN       NaN       NaN  ...       NaN       NaN       NaN
75        NaN       NaN       NaN  ...       NaN       NaN       NaN
78        NaN       NaN       NaN  ...       NaN       NaN       NaN
79        NaN       NaN       NaN  ...       NaN       NaN       NaN
81        NaN       NaN       NaN  ...       NaN       NaN       NaN
92        NaN       NaN       NaN  ...       NaN       NaN       NaN
118       NaN       NaN       NaN  ...       NaN       NaN       NaN
121       NaN       NaN       NaN  ...       NaN       NaN       NaN
124       NaN  0.000043  0.000042  ...       NaN       NaN       NaN
125       NaN       NaN       NaN  ...       NaN       NaN       NaN
133       NaN       NaN       NaN  ...       NaN       NaN       NaN
138       NaN       NaN       NaN  ...       NaN       NaN -0.000055
149       NaN       NaN       NaN  ...       NaN       NaN       NaN
156       NaN       NaN       NaN  ...       NaN       NaN       NaN
163       NaN       NaN       NaN  ...       NaN       NaN       NaN
166       NaN       NaN       NaN  ...       NaN       NaN       NaN
177       NaN       NaN       NaN  ...       NaN       NaN       NaN
180       NaN       NaN       NaN  ...       NaN       NaN       NaN
184       NaN       NaN       NaN  ...       NaN       NaN       NaN
185       NaN       NaN       NaN  ...       NaN       NaN       NaN
191       NaN       NaN       NaN  ...       NaN       NaN       NaN

               silkworm                   swine               wolverine  \
        other      self     other          self         other      self
0         NaN       NaN       NaN           NaN           NaN       NaN
6         NaN       NaN       NaN           NaN           NaN       NaN
8         NaN       NaN       NaN           NaN           NaN       NaN
16        NaN       NaN       NaN           NaN           NaN       NaN
36        NaN       NaN       NaN           NaN           NaN       NaN
44        NaN       NaN       NaN           NaN           NaN       NaN
71        NaN       NaN       NaN           NaN           NaN       NaN
75        NaN       NaN       NaN           NaN           NaN       NaN
78        NaN       NaN       NaN           NaN           NaN       NaN
79        NaN       NaN       NaN           NaN           NaN       NaN
81        NaN       NaN       NaN           NaN           NaN       NaN
92        NaN       NaN       NaN           NaN           NaN       NaN
118       NaN       NaN       NaN           NaN           NaN       NaN
121       NaN       NaN       NaN           NaN           NaN       NaN
124       NaN       NaN       NaN           NaN           NaN       NaN
125       NaN -0.000017 -0.000017           NaN           NaN       NaN
133       NaN       NaN       NaN           NaN           NaN       NaN
138 -0.000055       NaN       NaN           NaN           NaN       NaN
149       NaN       NaN       NaN           NaN           NaN       NaN
156       NaN       NaN       NaN           NaN           NaN       NaN
163       NaN       NaN       NaN           NaN           NaN       NaN
166       NaN       NaN       NaN           NaN           NaN       NaN
177       NaN       NaN       NaN           NaN           NaN       NaN
180       NaN       NaN       NaN           NaN           NaN       NaN
184       NaN       NaN       NaN           NaN           NaN -0.000006
185       NaN       NaN       NaN           NaN           NaN       NaN
191       NaN       NaN       NaN -4.676630e-08 -4.676000e-08       NaN


        other
0         NaN
6         NaN
8         NaN
16        NaN
36        NaN
44        NaN
71        NaN
75        NaN
78        NaN
79        NaN
81        NaN
92        NaN
118       NaN
121       NaN
124       NaN
125       NaN
133       NaN
138       NaN
149       NaN
156       NaN
163       NaN
166       NaN
177       NaN
180       NaN
184 -0.000006
185       NaN
191       NaN

[27 rows x 62 columns]

In [8]:
original_data = pd.read_csv('../forager/data/fluency_lists/participant_data/transformed-data.csv')
original_data

           ID    Word
0     CAF-657  lizard
1     CAF-657     cat
2     CAF-657    hawk
3     CAF-657     dog
4     CAF-657  turtle
...       ...     ...
1209  SZA-781   puppy
1210  SZA-781  kitten
1211  SZA-781   goose
1212  SZA-781    duck
1213  SZA-781    wolf

[1214 rows x 2 columns]

In [9]:
old_data = pd.read_csv('../old_data/new_data.csv')
old_data

           ID    Word
0     CAF-657  lizard
1     CAF-657     cat
2     CAF-657    hawk
3     CAF-657     dog
4     CAF-657  turtle
...       ...     ...
1209  SZA-781   puppy
1210  SZA-781  kitten
1211  SZA-781   goose
1212  SZA-781    duck
1213  SZA-781    wolf

[1214 rows x 2 columns]

In [11]:
print(original_data.compare(old_data))

Empty DataFrame
Columns: []
Index: []

In [46]:
original_model = pd.read_csv("outputs/model_results.csv")
original_model = original_model.groupby(['dimension', 'type'])
original_model = original_model.get_group((100, 'alpha_0.3_w2v'))
original_model = original_model.reset_index(drop=True)
original_model = original_model.round(3)
original_model

,dimension,type,model,group,sum_NLL,mean_beta_semantic,mean_beta_freq,mean_beta_phon
0,100,alpha_0.3_w2v,forage_static,NH,3568.918,2.162,8.439,NaN
1,100,alpha_0.3_w2v,forage_dynamic_simdrop,NH,3486.998,3.328,8.371,NaN
2,100,alpha_0.3_w2v,forage_dynamic_multimodal_alpha=0.0,NH,3577.882,2.140,8.339,NaN
3,100,alpha_0.3_w2v,forage_dynamic_multimodal_alpha=0.1,NH,3540.589,2.784,8.195,NaN
4,100,alpha_0.3_w2v,forage_dynamic_multimodal_alpha=0.2,NH,3539.691,2.789,8.200,NaN
...,...,...,...,...,...,...,...,...
313,100,alpha_0.3_w2v,forage_phonologicaldynamicswitch_delta_rise=1....,CI,2938.184,5.067,8.551,-0.060
314,100,alpha_0.3_w2v,forage_phonologicaldynamicglobal_delta_rise=1....,CI,2906.895,4.949,8.861,-0.040
315,100,alpha_0.3_w2v,forage_phonologicaldynamiclocal_delta_rise=1.0...,CI,2886.660,6.237,8.916,-0.351
316,100,alpha_0.3_w2v,forage_phonologicaldynamicswitch_delta_rise=1....,CI,2920.222,4.636,8.790,-0.136
317,100,alpha_0.3_w2v,forage_random_baseline,CI,3461.678,0.000,0.000,NaN

In [47]:
old_model = pd.read_csv("../old_data/model_results.csv")
old_model = old_model.groupby(['dimension', 'type'])
old_model = old_model.get_group((100, 'alpha_0.3_w2v'))
old_model = old_model.reset_index(drop=True)
old_model = old_model.round(3)
old_model

,dimension,type,model,group,sum_NLL,mean_beta_semantic,mean_beta_freq,mean_beta_phon
0,100,alpha_0.3_w2v,forage_static,NH,3568.918,2.162,8.439,NaN
1,100,alpha_0.3_w2v,forage_dynamic_simdrop,NH,3486.998,3.328,8.371,NaN
2,100,alpha_0.3_w2v,forage_dynamic_multimodal_alpha=0.0,NH,3577.882,2.140,8.339,NaN
3,100,alpha_0.3_w2v,forage_dynamic_multimodal_alpha=0.1,NH,3540.589,2.784,8.195,NaN
4,100,alpha_0.3_w2v,forage_dynamic_multimodal_alpha=0.2,NH,3539.691,2.789,8.200,NaN
...,...,...,...,...,...,...,...,...
313,100,alpha_0.3_w2v,forage_phonologicaldynamicswitch_delta_rise=1....,CI,2938.184,5.067,8.551,-0.061
314,100,alpha_0.3_w2v,forage_phonologicaldynamicglobal_delta_rise=1....,CI,2906.895,4.949,8.861,-0.040
315,100,alpha_0.3_w2v,forage_phonologicaldynamiclocal_delta_rise=1.0...,CI,2886.660,6.237,8.916,-0.342
316,100,alpha_0.3_w2v,forage_phonologicaldynamicswitch_delta_rise=1....,CI,2920.222,4.636,8.790,-0.149
317,100,alpha_0.3_w2v,forage_random_baseline,CI,3461.678,0.000,0.000,NaN

In [48]:
print(original_model.compare(old_model))

    mean_beta_semantic         mean_beta_freq       mean_beta_phon
                  self   other           self other           self  other
43                 NaN     NaN            NaN   NaN         -0.170 -0.177
46                 NaN     NaN            NaN   NaN         -1.211 -1.136
49                 NaN     NaN            NaN   NaN         -1.747 -1.765
52                 NaN     NaN            NaN   NaN         -1.939 -1.896
55                 NaN     NaN            NaN   NaN         -1.620 -1.628
..                 ...     ...            ...   ...            ...    ...
309             10.040  15.261            NaN   NaN         -0.578 -0.765
312              9.143  10.569            NaN   NaN         -0.532 -0.582
313                NaN     NaN            NaN   NaN         -0.060 -0.061
315                NaN     NaN            NaN   NaN         -0.351 -0.342
316                NaN     NaN            NaN   NaN         -0.136 -0.149

[82 rows x 6 columns]

In [49]:
print(original_model.iloc[309])

dimension                                                           100
type                                                      alpha_0.3_w2v
model                 forage_phonologicaldynamiclocal_delta_rise=1.0...
group                                                                CI
sum_NLL                                                        2912.684
mean_beta_semantic                                                10.04
mean_beta_freq                                                    8.624
mean_beta_phon                                                   -0.578
Name: 309, dtype: object

In [60]:
dimensions = [50, 100, 200, 300]

type = [
    'alpha_0.0_s2v', # = alpha_1_w2v
    'alpha_0.0_w2v', # = alpha_1_s2v 
    'alpha_0.1_s2v', # = alpha_0.9_w2v
    'alpha_0.1_w2v', # = alpha_0.9_s2v
    'alpha_0.2_s2v', # = alpha_0.8_w2v
    'alpha_0.2_w2v', # = alpha_0.8_s2v
    'alpha_0.3_s2v', # = alpha_0.7_w2v
    'alpha_0.3_w2v', # = alpha_0.7_s2v 
    'alpha_0.4_s2v', # = alpha_0.6_w2v
    'alpha_0.4_w2v', # = alpha_0.6_s2v
    'alpha_0.5_s2v', # = alpha_0.5_w2v
    'average',
    'only_w2v',
    'only_s2v'
]
boolean = [] 
for dim in dimensions: 
    for t in type: 
        df = pd.read_csv("../forager/output/" + str(dim) + "_dim_results/" + t + "_results/model_results.csv")
        boolean.append(df.isin(["CBM-702"]).any().any())
        boolean.append(df.isin(["SIZ-390"]).any().any())
print(False in boolean)

boolean

False

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [72]:
participant_data = pd.read_csv("../forager/data/fluency_lists/participant_data/transformed-data.csv")
set(participant_data['ID'].tolist())

{'CAF-657',
 'CAJ-663',
 'CAM-666',
 'CAP-671',
 'CAQ-672',
 'CAR-673',
 'CAS-674',
 'CAV-678',
 'CAY-681',
 'CBD-686',
 'CBF-691',
 'CBH-693',
 'CBJ-697',
 'CBL-698',
 'CBM-702',
 'CBP-707',
 'CBS-711',
 'CBW-715',
 'CCB-720',
 'CCC-721',
 'CCD-722',
 'CCF-724',
 'CCH-726',
 'CCL-730',
 'CCX-744',
 'CDG-753',
 'CDH-754',
 'CDM-759',
 'CDR-764',
 'CDU-767',
 'SGO-159',
 'SIU-211',
 'SIZ-390',
 'SKE-234',
 'SMK-401',
 'SNI-300',
 'SNR-308',
 'SNT-310',
 'SNV-312',
 'SNY-315',
 'SOE-320',
 'SOQ-329',
 'SOX-335',
 'SPA-338',
 'SPC-340',
 'SPH-344',
 'SPL-436',
 'SPV-450',
 'SPX-452',
 'SRF-483',
 'SRR-498',
 'SSG-520',
 'SSZ-539',
 'SUG-544',
 'SUT-556',
 'SUV-558',
 'SVA-563',
 'SVH-570',
 'SVY-587',
 'SZA-781'}

In [40]:
import pandas as pd

data = pd.read_csv("../forager/data/fluency_lists/participant_data/raw-data.txt", sep="\t")
words = list(set(data['Word'].tolist()))

w2v_s2v_vocab = pd.read_csv("../forager/data/lexical_data/Embeddings/Speech2Vec/speech2vec_200.txt", sep=" ", skiprows=1)

In [47]:
words

['pig',
 'sealion',
 'goat',
 'cow',
 'worm',
 'saber_tooth_cat',
 'barracuda',
 'killer',
 'lobster',
 'bunny',
 'stingray',
 'stork',
 'scorpion',
 'rooster',
 'coyote',
 'bull',
 'raven',
 'octopus',
 'meerkat',
 'mosquito',
 'fox',
 'cub',
 'toucan',
 'spider',
 'zebra',
 'millipede',
 'bear',
 'eagle',
 'swan',
 'cheetah',
 'panda',
 'puppy',
 'snake',
 'wombat',
 'hyena',
 'reptile',
 'panther',
 'elephant',
 'dragonfly',
 'beetle',
 'stickbug',
 'buffalo',
 'cricket',
 'squirrel',
 'skunk',
 'firefly',
 'alligator',
 'monkey',
 'ostrich',
 'polar',
 'caribou',
 'tigerfish',
 'porcupine',
 'baboon',
 'fly',
 'crane',
 'jaguar',
 'dog',
 'moth',
 'catfish',
 'lice',
 'kitten',
 'bobcat',
 'ox',
 'pony',
 'woodpecker',
 'toad',
 'lioness',
 'elk',
 'kudu',
 'fish',
 'monster',
 'oxen',
 'peacock',
 'bug',
 'parrot',
 'hedgehog',
 'capybara',
 'crocodile',
 'snail',
 'bulldog',
 'bluejay',
 'duck',
 'parakeet',
 'dinosaur',
 'terrier',
 'sheep',
 'chipmunk',
 'macaw',
 'manatee',
 'buck',
 'tadpole',
 'tiger',
 'chicken',
 'centipede',
 'boar',
 'ant',
 'human',
 'cougar',
 'rabbit',
 'triceratops',
 'ferret',
 'caterpillar',
 'lion',
 'jellyfish',
 'ladybug',
 'gerbil',
 'badger',
 'mammoth',
 'turkey',
 'dragon',
 'moose',
 'flamingo',
 'mule',
 'groundhog',
 'robin',
 'goldfish',
 'shark',
 'crow',
 'bee',
 'prairie',
 'goose',
 'lemur',
 'seahorse',
 'kangaroo',
 'falcon',
 'pelican',
 'seagull',
 'piranha',
 'deer',
 'guinea',
 'eel',
 'shepherd',
 'ape',
 'pilgrim',
 'hawk',
 'squid',
 'gecko',
 'possum',
 'frog',
 'crab',
 'pegasus',
 'waterbug',
 'horse',
 'stegosaurus',
 'emu',
 'not_snails',
 'chihuahua',
 'gopher',
 'flea',
 'owl',
 'ring_tailed',
 'raccoon',
 'rainbow',
 'rhino',
 'iguana',
 'beaver',
 'tarantula',
 'grizzly',
 'chimp',
 'fowl',
 'wolf',
 'walrus',
 'bird',
 'penguin',
 'girdle',
 'hippo',
 'whale',
 'mouse',
 'tortoise',
 'lizard',
 'wildebeest',
 'gorilla',
 'platypus',
 'sloth',
 'clownfish',
 'hen',
 'donkey',
 'dolphin',
 't_rex',
 'anteater',
 'shrimp',
 'armadillo',
 'camel',
 'rat',
 'koala',
 'stinkbug',
 'pigeon',
 'chick',
 'butterfly',
 'cat',
 'leopard',
 'seadragon',
 'cardinal',
 'antelope',
 'orangutan',
 'seal',
 'giraffe',
 'insect',
 'turtle',
 'hog',
 'gazelle',
 'lamb',
 'angelfish',
 'bat',
 'oscar',
 'warthog',
 'wallaby',
 'hamster']

In [57]:
w2v_s2v_vocab = w2v_s2v_vocab['the'].tolist()
len(w2v_s2v_vocab['the'].tolist())

count = len([word for word in words if word not in w2v_s2v_vocab])

TypeError: list indices must be integers or slices, not str

In [55]:
count

59